### ISSUE TITLE
Java 9 changes

### ISSUE THREAD

**Issue by shathor** [JFXtras/jfxtras-labs#122]
Running 8.0-r5 with Java 9 produces following stacktrace:

`Caused by: java.lang.NoClassDefFoundError: javafx/scene/SnapshotParametersBuilder
	at jfxtras.labs.util.Util.<clinit>(Util.java:248)
	at ch.hsr.ogv.controller.ViewController.initialize(ViewController.java:685)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2573)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
	at javafx.fxml/javafx.fxml.FXMLLoader.load(FXMLLoader.java:2435)`

**Comment by tbee** [comment]
Correct. The still unreleased 9 branch (9.0-r1-SNAPSHOT) is intended for Java 9. Working on that, pretty close to a first release though.
