### ISSUE TITLE
Add Enum support to BeanPathAdapter

### ISSUE THREAD

**Issue by dennisfischer** [JFXtras/jfxtras-labs#25]
The current BeanPathAdapter fails supporting Enums and fails with this exception:
Reason: The used pojos field "visibility" is not set (null) - this may cause an illegalargumentexception if "valueOf" is called or in this case if "newInstance of Enum" is created. There is no way to handle this from my side. The only option is to define a default value for the pojo - which may not be wanted. There is no way to give the adapter a default value.
Example Code:

``` java
enum Visibility { DEFINIE_SOME_CONSTANTS; }

@FXML
ChoiceBox<Visibility>               uploadVisibility;
beanPathAdapter.bindBidirectional("upload.visibility", uploadVisibility.valueProperty(), Visibility.class);
```

```
Caused by: java.lang.IllegalArgumentException: Unable to get accessor return instance for MethodHandle()Visibility using class org.chaosfisch.youtubeuploader.db.data.Visibility.
    at jfxtras.labs.scene.control.BeanPathAdapter$FieldHandle.deriveValueFromAccessor(BeanPathAdapter.java:3198) ~[jfxtras-labs-2.2-r5-SNAPSHOT.jar:na]
    at jfxtras.labs.scene.control.BeanPathAdapter$FieldProperty.setDerived(BeanPathAdapter.java:1751) ~[jfxtras-labs-2.2-r5-SNAPSHOT.jar:na]
    at jfxtras.labs.scene.control.BeanPathAdapter$FieldProperty.<init>(BeanPathAdapter.java:1727) ~[jfxtras-labs-2.2-r5-SNAPSHOT.jar:na]
    at jfxtras.labs.scene.control.BeanPathAdapter$FieldBean.performOperation(BeanPathAdapter.java:1289) ~[jfxtras-labs-2.2-r5-SNAPSHOT.jar:na]
    at jfxtras.labs.scene.control.BeanPathAdapter$FieldBean.performOperation(BeanPathAdapter.java:1280) ~[jfxtras-labs-2.2-r5-SNAPSHOT.jar:na]
    at jfxtras.labs.scene.control.BeanPathAdapter$FieldBean.performOperation(BeanPathAdapter.java:1144) ~[jfxtras-labs-2.2-r5-SNAPSHOT.jar:na]
    at jfxtras.labs.scene.control.BeanPathAdapter.bindBidirectional(BeanPathAdapter.java:560) ~[jfxtras-labs-2.2-r5-SNAPSHOT.jar:na]
```

Possible solution - around line 3198 add - this correctly sets the value to null. Alternative: Set one of the enum constants as targetValue, this is a design issue however. I prefer the null value.

``` java
} else if (clazz.isEnum()) {
    targetValue = null;
}
```

**Comment by ugate** [comment]
Thanks for the input Dennis. I'll look into ways to accommodate your request.

**Comment by dennisfischer** [comment]
In the google group I posted sth about this: https://groups.google.com/forum/?fromgroups=#!topic/jfxtras-users/VwaA84GiMt0
Binding to custom types with non trivial constructors (for example java.io.File) doesn't work. The adapter tries to create a new instance of this class and fails with an exception

Possible solution:
Add a possibility to set a default value for custom types
OR
Use as default value "null" instead of newInstance(). This will automatically add support for enums and custom data types with non trivial constructors.

**Comment by ugate** [comment]
Dennis- I responded to the post you referenced. I would like to get your feedback for a design solution for implementing custom types (defaulting to null would break path traversal unless the POJO path(s) are instantiated prior to binding). If the adapter provides some sort of generic factory-like pattern we may be able to solve most of the issues you (and possibly others) are experiencing.

**Comment by walec51** [comment]
I fail to see why this class even tries to create a new instance when the property getter returns null. Null is an important business value. You cannot just carelessly replace it.

**Comment by ugate** [comment]
I agree that null is pertinent. The reason an attempt is made to create a new instance is to avoid burdening the user with prepopluating every property that bound "paths" represent. If new instance was not called, every property on the pojo would have to be set before binding (even pojos within pojos) or new values could never be set from a bound control (which defeats the purpose of binding in the first place). For this reason I believe the use of new instance is favorable enough to preponderate over the use of null. 

Maybe a better solution would be a factory that could be customized to either return a new instance (default) or null (if you so choose).

**Comment by tbee** [comment]
Closed because of inactivity
