### ISSUE TITLE
JPA & library

### ISSUE THREAD

**Issue by FabianCamargo** [JFXtras/jfxtras-labs#41]
I am developing a project using jpa EclipseLink 2.0 and the controls of jfxtras, but seems that XMLParser class are incompatibles and i can initialize the persistence unit, when i add the jar of javafxstras i got the exception when i try to create the EntityManagerFactory(1. URI was not reported to parser for entity [document])
    at org.eclipse.persistence.internal.jpa.deployment.xml.parser.XMLExceptionHandler.error(XMLExceptionHandler.java:28)
    at org.eclipse.persistence.internal.jpa.deployment.xml.parser.XMLExceptionHandler.warning(XMLExceptionHandler.java:23)
    at gnu.xml.aelfred2.SAXDriver.warn(SAXDriver.java:935)
    at gnu.xml.aelfred2.SAXDriver.startExternalEntity(SAXDriver.java:631)
    at gnu.xml.aelfred2.XmlParser.pushURL(XmlParser.java:3358)
    at gnu.xml.aelfred2.XmlParser.doParse(XmlParser.java:159)
    at gnu.xml.aelfred2.SAXDriver.parse(SAXDriver.java:320)
    at gnu.xml.aelfred2.XmlReader.parse(XmlReader.java:294)
    at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.processPersistenceXML(PersistenceUnitProcessor.java:577)
    ... 69 more

**Comment by tbee** [comment]
I'd suggest you also put this on Eclipselink's mailing list, because Eclipselink is, AFAIK, completely encapsulated (has all external jars it uses repackaged to org.eclipse.pesistence.*). So I'm a bit amazed it uses gnu.xml.

Tom

PS: I use Eclipselink (2.4.0) a lot in my projects, but have not tried a combination with JFX

**Comment by tbee** [comment]
Closed because of inactivity
